version: '3.9'

networks:
  mrrobot:

services:
  php:
    container_name: php_comtainer
    image: php:8.1-fpm-alpine
    ports:
      - "9000:9000"
    volumes:
      - ./src:/code
    networks:
      - mrrobot

  nginx:
    container_name: nginx_container
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mrrobot
  mysql:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
      MYSQL_DATABASE: 'magnercare'

    ports:
      - "3306:3306"
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    networks:
      - mrrobot

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 512M
    restart: always
    ports:
      - 88:80
    networks:
      - mrrobot

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./docker/redisdata:/data
    networks:
      - mrrobot

  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongodb:/data/db
    networks:
      - mrrobot

